### ISSUE TITLE
Compatibility with PowerStore 3.6.0.0 ?

### ISSUE THREAD

**Issue by wrbst** [dell/python-powerstore#18]
Hello is the current version of python-powerstore (2.1.0) compatible with PowerStore OS 3.6.0.0 ?

**Comment by Bhavneet-Sharma** [comment]
Hi @wrbst ,

Thank you for reaching out to us. Yes this current version of python-powerstore(2.1.0) is compatible with PowerStore OS 3.6.x.

**Comment by wrbst** [comment]
Thank you!
