### ISSUE TITLE
auth_token not set properly in client

### ISSUE THREAD

**Issue by ShawnEsterman** [dell/python-powerstore#21]
I am seeing an issue when using this package that it makes a login event for every API call I make using the package. It ends up being a huge performance hit and generates a lot of splunk logs for auditing. Through some troubleshooting and referencing your documentation, it seems that the referenced line below does not properly set an `auth_token` as defined in the API docs. 

https://github.com/dell/python-powerstore/blob/c3abb6dde71ead8d80d44b2eea872cfc0abb9e73/PyPowerStore/client.py#L147

In my troubleshooting, I found that the value of the header `set-cookie` is not a token value, but a bunch of properties that the API wants to see in the cookie for the requests and this includes `auth_token`. However, since this client doesn't utilize a requests Session it does not seem to save cookies.

It would be nice to see if this client could be ported to use requests Session so that the cookies are automatically set when you hit the login_session endpoint (Still would have to set the DELL-EMC-TOKEN as a header though). Otherwise, it might be easier to cache the cookies attribute returned by the response object of the login_session endpoint. Then use the `cookies` param on each rest request method to ensure that the token is properly set and a reauth does not occur with every call. [Reference](https://3.python-requests.org/user/quickstart/?highlight=cookies#cookies)

**Comment by wrbst** [comment]
Any update on this [Bhavneet-Sharma](https://github.com/Bhavneet-Sharma) ?

**Comment by kuttattz** [comment]
Hi @ShawnEsterman @wrbst

The fix for this issue has been released in the PyPowerStore library, which can be found on GitHub (https://github.com/dell/python-powerstore) and PyPI (https://pypi.org/project/PyPowerStore/).

**Comment by anupamaloke** [comment]
Closed by #27
